#Set
In Python, a set is an unordered collection of unique elements. Sets are commonly used for membership testing, removing duplicates from a sequence, and performing mathematical operations like union, intersection, difference, and symmetric difference.

###Creating a Set
You can create a set using curly braces { } or the set( ) function:

In [ ]:
# Using curly braces
my_set = {1, 2, 3, 4}

# Using set() function
my_set = set([1, 2, 3, 4])

###Set Methods

In [1]:
#add(element): Adds a single element to the set.
my_set = {1, 2, 3}
my_set.add(4)
# my_set is now {1, 2, 3, 4}
my_set

{1, 2, 3, 4}

In [2]:
#remove(element): Removes a single element from the set.
my_set = {1, 2, 3}
my_set.remove(2)
# my_set is now {1, 3}
my_set

{1, 3}

In [3]:
#discard(element): Removes a single element from the set.
my_set = {1, 2, 3}
my_set.discard(2)
my_set.discard(4)  # No error raised
# my_set is now {1, 3}
my_set

{1, 3}

In [4]:
#pop(): Removes and returns an arbitrary element from the set. Raises a KeyError if the set is empty.
my_set = {1, 2, 3}
element = my_set.pop()
# element could be 1, 2, or 3; my_set is now reduced by one element
element

1

In [5]:
#clear(): Removes all elements from the set
my_set = {1, 2, 3}
my_set.clear()
# my_set is now set()
my_set

set()

##for practice:

Set Creation:

•	Create a set containing the elements 'apple', 'banana', and 'cherry'.

•	Convert a list [1, 2, 2, 3, 4, 4] into a set and verify the result.

•	Create an empty set and add three different elements to it.

Add:

•	Add the element 'orange' to a set containing 'apple' and 'banana'.

•	Add the number 10 to a set of numbers from 1 to 5.

•	Add a new element to an existing set and print the updated set.

Remove:

•	Remove the element 'banana' from a set containing 'apple', 'banana', and 'cherry'.



•	Consider a set colors = {'red', 'green', 'blue', 'yellow'}. Remove the color 'green' from the set and print the set before and after the removal operation.

Discard:

•	Discard the element 'grape' from a set containing 'apple', 'banana', and 'cherry'.

•	Discard the number 7 from a set {1, 2, 3, 4, 5} and verify that no error is raised.



Pop:

•	Pop an element from a set {10, 20, 30, 40} and print the popped element.

•	Pop elements from a set one by one until it is empty and print each element.



Clear:

•	Clear all elements from a set containing {1, 2, 3, 4, 5}.

•	Create a set fruits, clear it, and then add the fruits 'apple', 'banana', and 'orange' to it.

###Set Operations:

In [6]:
#union(*others): Returns a new set with elements from the set and all others
set1 = {1, 2, 3}
set2 = {3, 4, 5}
set3 = set1.union(set2)
# set3 is {1, 2, 3, 4, 5}
set3

{1, 2, 3, 4, 5}

In [7]:
#update(*others): Updates the set, adding elements from all others
set1 = {1, 2, 3}
set2 = {3, 4, 5}
set1.update(set2)
# set1 is now {1, 2, 3, 4, 5}
set1

{1, 2, 3, 4, 5}

In [8]:
#intersection(*others): Returns a new set with elements common to the set and all others.
set1 = {1, 2, 3}
set2 = {2, 3, 4}
set3 = set1.intersection(set2)
# set3 is {2, 3}
set3

{2, 3}

In [9]:
#intersection_update(*others): Updates the set, keeping only elements found in it and all others.
set1 = {1, 2, 3}
set2 = {2, 3, 4}
set1.intersection_update(set2)
# set1 is now {2, 3}
set1

{2, 3}

In [10]:
#difference(*others): Returns a new set with elements in the set that are not in the others.
set1 = {1, 2, 3}
set2 = {2, 3, 4}
set3 = set1.difference(set2)
# set3 is {1}
set3

{1}

In [11]:
#difference_update(*others): Updates the set, removing elements found in others
set1 = {1, 2, 3}
set2 = {2, 3, 4}
set1.difference_update(set2)
# set1 is now {1}
set1

{1}

In [12]:
#symmetric_difference(other): Returns a new set with elements in either the set or other but not both.
set1 = {1, 2, 3}
set2 = {2, 3, 4}
set3 = set1.symmetric_difference(set2)
# set3 is {1, 4}
set3

{1, 4}

In [13]:
#symmetric_difference_update(other): Updates the set,
#keeping only elements found in either set but not both.
set1 = {1, 2, 3}
set2 = {2, 3, 4}
set1.symmetric_difference_update(set2)
# set1 is now {1, 4}
set1

{1, 4}

##for practice:
####Set Operations
1.	Union:

o	Create a union of sets {1, 2, 3} and {3, 4, 5}.

o	Find the union of three sets: {1, 2}, {2, 3}, and {3, 4}.




2.	Update:

o	Update a set {1, 2, 3} with elements from another set {4, 5, 6}.

o	Given the set main_set = {1, 2, 3} and two other sets set1 = {4, 5} and set2 = {6, 7}, use the update method to add elements from set1 and set2 to main_set. What is the resulting set?

o	You have a set base_set = {'apple', 'banana'} and you want to update it with elements from the sets extras1 = {'cherry', 'date'} and extras2 = {'fig', 'grape'}. Use the update method to add elements from extras1 and extras2 to base_set. What does the base_set contain after the operation?

o	Consider a set inventory = {'sword', 'shield'}. Update this set with elements from the sets new_items1 = {'potion', 'armor'} and new_items2 = {'helm', 'ring'} using the update method. What is the state of the inventory set after updating it with the elements from new_items1 and new_items2?





3.	Intersection:

o	Find the intersection of sets {1, 2, 3} and {2, 3, 4}.

o	Create an intersection of three sets: {1, 2}, {2, 3}, and {2, 4}.






4.	Intersection Update:

o	Update a set {1, 2, 3, 4} to keep only elements also in {2, 3, 5}.


o	Given the set set1 = {1, 2, 3, 4, 5} and the set set2 = {4, 5, 6, 7}, use the intersection_update method to update set1 to contain only elements that are common between set1 and set2. What elements remain in set1 after the operation?

o	You have a set fruits = {'apple', 'banana', 'cherry', 'date'} and another set groceries = {'banana', 'milk', 'bread', 'apple'}. Use the intersection_update method to modify the fruits set to retain only fruits that are also present in the groceries set. What does the updated fruits set contain?

o	Consider the set inventory = {'sword', 'shield', 'potion', 'armor'} and two other sets loot1 = {'sword', 'potion', 'ring'} and loot2 = {'armor', 'gold', 'potion'}. Use the intersection_update method to update the inventory set to retain only items that are common across all sets. What items are left in the inventory set after the operation?




5.	Difference:

o	Find the difference between sets {1, 2, 3} and {2, 3, 4}.



o	Given the set set1 = {1, 2, 3, 4, 5} and the set set2 = {3, 4, 6}, use the difference operation to create a new set that contains elements from set1 that are not in set2. What is the resulting set?

o	You have a set colors1 = {'red', 'green', 'blue'} and a set colors2 = {'blue', 'yellow'}. Use the difference method to find the elements in colors1 that are not in colors2. What does the new set contain?


o	Consider the set items = {'book', 'pen', 'notebook', 'eraser'} and another set to_remove = {'pen', 'pencil'}. Use the difference operation to create a set that contains elements in items but not in to_remove. What are the elements in the resulting set?





6.	Difference Update:

o	Update a set {1, 2, 3, 4} by removing elements found in {2, 3}.


o	Given the set numbers = {1, 2, 3, 4, 5, 6} and the set to_remove = {3, 4, 7}, use difference_update to remove the elements in to_remove from numbers. What is the resulting set?


o	You have a set fruits = {'apple', 'banana', 'cherry', 'date'}. Use difference_update to remove the elements {'banana', 'date'} from the fruits set. What is the state of the fruits set after the operation?


o	Consider a set inventory = {'sword', 'shield', 'potion', 'armor'}. Use difference_update with the list ['potion', 'armor', 'ring'] to remove the specified elements from the inventory set. What does the inventory set contain after performing the difference_update operation?






7.	Symmetric Difference:

o	Find the symmetric difference between sets {1, 2, 3} and {2, 3, 4}.

o	Given the set set1 = {1, 2, 3, 4, 5} and the set set2 = {4, 5, 6, 7}, use the symmetric_difference operation to find the elements that exist in either set1 or set2, but not in both. What elements are in the resulting set?

o	You have a set colors1 = {'red', 'green', 'blue'} and another set colors2 = {'blue', 'yellow'}. Use the symmetric_difference operation to find the colors that are present in either colors1 or colors2, but not in both. What are the colors in the resulting set?

o	Consider the set inventory1 = {'sword', 'shield', 'potion', 'armor'} and another set inventory2 = {'armor', 'gold', 'potion', 'ring'}. Use the symmetric_difference operation to find the items that are present in either inventory1 or inventory2, but not in both. What items are in the resulting set?





8.	Symmetric Difference Update:

o	Update a set {1, 2, 3} to keep elements found in either {2, 3, 4} but not both.

o	Given the set set1 = {1, 2, 3, 4, 5} and the set set2 = {4, 5, 6, 7}, use the symmetric_difference_update method to modify set1 to contain elements that are unique to each set. What is the resulting set after the operation?

o	You have a set letters1 = {'a', 'b', 'c', 'd'} and another set letters2 = {'c', 'd', 'e', 'f'}. Use the symmetric_difference_update method to modify the letters1 set to contain only letters that are unique to each set. What does the updated letters1 set contain?

o	Consider the set inventory1 = {'sword', 'shield', 'potion', 'armor'} and another set inventory2 = {'armor', 'gold', 'potion', 'ring'}. Use the symmetric_difference_update method to modify the inventory1 set to contain only items that are unique to each inventory. What items are in the inventory1 set after the operation?

###Subset and Superset Checks:

In [ ]:
#issubset(other): Returns True if the set is a subset of other
set1 = {1, 2}
set2 = {1, 2, 3}
set1.issubset(set2)
# returns True

In [ ]:
#issuperset(other): Returns True if the set is a superset of other
set1 = {1, 2, 3}
set2 = {1, 2}
set1.issuperset(set2)
# returns True

##for practice:


Subset and Superset Checks

1.	Issubset:

o	Check if set {1, 2} is a subset of {1, 2, 3}.

o	Verify if a set {4, 5} is a subset of another set {1, 2, 3, 4, 5}.



2.	Issuperset:

o	Check if set {1, 2, 3} is a superset of {1, 2}.

o	Verify if a set {1, 2, 3, 4, 5} is a superset of another set {4, 5}.